### ISSUE TITLE
Dúvida andamento do desenvolvimento

### ISSUE THREAD

**Issue by deniscsz** [bittools/skyhub-magento-2#1]
@tiagosampaio acredito que você está desenvolvendo o módulo mas ainda não está finalizado visto que o branch master não está com arquivos. Eu estou com uma demanda para fazer essa integração. Caso ainda tenha muita implementação a ser feita no módulo, tenho interesse em ajudar, afinal é uma necessidade de um cliente meu também. 

Se tiver interesse em ajuda, acredito que criar um community board aqui no github seria interessante.
Abraço.

**Comment by tiagosampaio** [comment]
Olá @deniscsz, tudo bem?

O módulo está em fase de testes. Em breve liberaremos para a comunidade.

Abraços!

**Comment by deniscsz** [comment]
@tiagosampaio Tudo certo.
Obrigado pelo retorno.
