### ISSUE TITLE
Erro ao alterar produto no magento e salvar

### ISSUE THREAD

**Issue by kshopcombr** [bittools/skyhub-magento-2#9]
Atualizamos para a versão mais nova do modulo porem fica dando erro quando atualizo algo nos anuncio, segue abaixo o erro

The product cannot be integrated: Warning: json_decode() expects parameter 1 to be string, array given in /home/kshop/public_html/vendor/bittools/skyhub-m2/Model/Config/SkyhubAttributes/Data.php on line 53

**Comment by tiagoTescaRoramos** [comment]
Bom dia 

Eita, estranho hem, vou ver o pq e te retorno @kshopcombr

**Comment by kshopcombr** [comment]
Ok, voltei para 1.0.12 funcionou normalmente @tiagoTescaRoramos

**Comment by tiagoTescaRoramos** [comment]
Correção efetuada na versão 1.0.14

Obrigado
